project:
  type: website

website:
  title: "My Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Research.qmd
        text: Research
      - href: Contact.qmd
        text: Contact
    right:
      - text: "GitHub"
        icon: fab fa-github  # Font Awesome icon
        href: https://github.com/floKuehl
      - text: "Twitter"
        icon: fab fa-twitter
        href: https://twitter.com/FloKuehlwein


format:
  html:
    theme: flatly
    css: styles.css
    toc: true


